version: "3.8"
services:
  mongo:
    container_name: mongo-cryptotao-test-code
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  cryptotao:
    container_name: api-cryptotao-test-code
    image: api-cryptotao-test-code
    restart: always
    depends_on: 
      - mongo
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "3000:3000"
    external_links:
      - mongo